# (C) 2019 Crafted by Roberto Nogueira
# email : roberto.nogueira@tecnogrupo.com.br.com
# trello: robertonogueira17

olimpia: env MYSQL_DATABASE_DEV=olimpia_dev rails server -p 3002
rioclaro: env MYSQL_DATABASE_DEV=rioclaro_dev rails server -p 3003
suzano: env MYSQL_DATABASE_DEV=suzano_dev rails server -p 3004
santoandre: env MYSQL_DATABASE_DEV=santoandre_dev rails server -p 3005
demo: env MYSQL_DATABASE_DEV=demo_dev rails server -p 3013
